# Generated by Django 3.0.1 on 2020-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioitem_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='short_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='sub_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
