# Generated by Django 3.0.1 on 2020-01-11 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_auto_20200111_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'verbose_name': 'Элемент портфолио', 'verbose_name_plural': 'Элементы портфолио'},
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='body',
            field=models.TextField(help_text='Полноценное описание проекта со всеми подробностями.', verbose_name='Подробное описание'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='img',
            field=models.FileField(blank=True, help_text='Картинка', null=True, upload_to='portfolio/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='short_description',
            field=models.TextField(help_text='Краткое описание видное при просмотре в списке.', null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='sub_title',
            field=models.CharField(help_text='Подзаголовок написанный серым цветом.', max_length=255, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
